apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{service}}
  namespace: {{namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{service}}
  template:
    metadata:
      labels:
        k8s-app: {{service}}
        version: v1
    spec:
      containers:
      - name: {{service}}
        image: {{image}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{namespace}}
  name: {{service}}
spec:
  selector:
    k8s-app: {{service}}
  ports:
  - port: 5672
    name: tcp
    protocol: TCP
  - port: 15672
    name: http
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{service}}
  namespace: {{namespace}}
spec:
  rules:
  - host: rabbitmq.{{team}}.cloud.school.thoughtworks.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: {{service}}
          servicePort: 15672
